services:
  postgres:
    image: postgres:16-alpine
    container_name: vps_checker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_super_secure_password_123
      POSTGRES_DB: vps_checker_hub
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - secure_network

volumes:
  pgdata:
    driver: local

networks:
  secure_network:
    driver: bridge
